import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from './Components/Sidebar/Sidebar';
import GlobalStyleProvider from './Providers/GlobalStyleProvider';
import ContextProvider from './Providers/ContextProvider';
import { ClerkProvider } from '@clerk/nextjs';
import Nav from './Components/Navbar/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ContextProvider>
            <GlobalStyleProvider>
              <Nav />
              <Sidebar />
              {children}
            </GlobalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
