import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '../components/sidebar/sidebar';
import GlobalStyleProvider from '../Providers/GlobalStyleProvider';
import ContextProvider from '../Providers/ContextProvider';
import { ClerkProvider } from '@clerk/nextjs';
import Nav from '../components/navbar/nav';
import Header from '../components/header/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: ' | SecondBrain',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ContextProvider>
              <Header/>
              <Nav />
            <GlobalStyleProvider>
              <Sidebar />
              {children}
            </GlobalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
